version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: root123!
      MYSQL_DATABASE: wonderfood
      MYSQL_USER: admin
      MYSQL_PASSWORD: root123!
    ports:
      - "3306:3306"