// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AtualizarCliente(ctx context.Context, arg AtualizarClienteParams) (sql.Result, error)
	AtualizarProduto(ctx context.Context, arg AtualizarProdutoParams) (sql.Result, error)
	DeletarPedido(ctx context.Context, numeropedido int32) error
	DeletarProduto(ctx context.Context, id string) error
	InserirCliente(ctx context.Context, arg InserirClienteParams) error
	InserirProduto(ctx context.Context, arg InserirProdutoParams) error
	ObterPedidoPorNumeroPedido(ctx context.Context, numeropedido int32) (Pedido, error)
	ObterProdutosPorCategoria(ctx context.Context, categoria int32) ([]Produto, error)
	ObterTodosProdutos(ctx context.Context) ([]Produto, error)
}

var _ Querier = (*Queries)(nil)
