basePath: /
definitions:
  dto.ProdutoDto:
    properties:
      categoria:
        type: integer
      descricao:
        type: string
      id:
        type: string
      nome:
        type: string
      valor:
        type: number
    type: object
  entity.CategoriaProduto:
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - Lanche
    - Bebida
    - Sobremesa
    - Acompanhamento
  entity.Produto:
    properties:
      categoria:
        $ref: '#/definitions/entity.CategoriaProduto'
      descricao:
        type: string
      id:
        type: string
      nome:
        type: string
      valor:
        type: number
    type: object
  handler.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: ff.oliveira32@gmail.com
    name: Felipe Fabricio
    url: https://www.linkedin.com/in/felipefabricio/
  description: API para o sistema de pedidos da WonderFood
  termsOfService: http://swagger.io/terms/
  title: WonderFood API
  version: "1.0"
paths:
  /produtos:
    get:
      consumes:
      - application/json
      description: Obtém todos os Produtos cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Produto'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Listar Produtos
      tags:
      - Produtos
    post:
      consumes:
      - application/json
      description: Cria um novo Produto
      parameters:
      - description: Request do Produto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ProdutoDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Inserir Produto
      tags:
      - Produtos
  /produtos/{categoria}:
    get:
      consumes:
      - application/json
      description: Obtém todos os Produtos cadastrados por Categoria de Produto
      parameters:
      - description: Categoria Produto
        in: path
        name: categoria
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Produto'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Listar Produto por Categoria de Produto
      tags:
      - Produtos
swagger: "2.0"
